Repository YU-RentCar/yurentcar-fe-admin, pull requests merged in 2023-11, with the labels that each got.

#3 [Chore/#2] actions 세팅
  .github/workflows/tempDeploy.yml
Labels: 📐 Chore

#5 [Feat/#4] SideBar 구현
  src/App.js
  src/components/.gitkeep
  src/components/SideBar.js
  src/pages/.gitkeep
  src/pages/CarState/CarState.js
Labels: ✨ Feat

#9 [Feat/#6] 차량 상태 관리 UI 및 로직 구현
  src/App.js
  src/api/carStateAxios.js
  src/components/SideBar.js
  src/pages/CarState/CarState.js
  src/pages/CarState/utils/useCarState.js
Labels: ✨ Feat

#11 [Feat/#8] 지도 관리 페이지 추가
  src/App.js
  src/components/SideBar.js
  src/pages/CarState/CarState.js
  src/pages/Map/Map.js
  src/pages/Map/ParkingMap/MapController.js
  src/pages/Map/ParkingMap/ParkingMap.js
  src/pages/Map/ParkingMap/colorSet.js
  src/pages/Map/ParkingMap/option.js
Labels: ✨ Feat

#13 [Feat/#10] 차량 관리 UI 및 로직 구현
  src/App.js
  src/api/carAxios.js
  src/api/manageCarAxios.js
  src/components/SideBar.js
  src/pages/Car/Car.js
  src/pages/Car/utils/useCar.js
  src/pages/ManageCar/Accident.js
  src/pages/ManageCar/DefaultInfo.js
  src/pages/ManageCar/DetailInfo.js
  src/pages/ManageCar/ManageCar.js
  src/pages/ManageCar/Repair.js
  src/pages/ManageCar/title.js
  src/popUp/Car/Delete.js
  src/recoil/manageCarAtom.js
  src/recoil/popUpInfoSelector.js
  src/utils/usePopUp.js
Labels: ✨ Feat

#15 [Feat/#12] 예약 변경 UI 구현
  src/App.js
  src/components/SideBar.js
  src/pages/Reservation/CarList/CarList.js
  src/pages/Reservation/CarList/utils/useCarList.js
  src/pages/Reservation/DateTime/DateTime.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/ResvList/ResvList.js
  src/pages/Reservation/ResvList/utils/useResvList.js
  src/recoil/reservationAtom.js
Labels: ✨ Feat

#16 [Feat/#14] 포인트 관리 UI 및 로직 구현
  src/App.js
  src/components/SideBar.js
  src/pages/Point/Point.js
  src/pages/Point/Record.js
  src/pages/Point/Search.js
  src/popUp/Point/Change.js
  src/recoil/pointAtom.js
Labels: ✨ Feat

#19 [Feat/#17] 차 키 관리 UI 및 로직 구현
  src/App.js
  src/components/SideBar.js
  src/pages/Key/Key.js
  src/pages/Key/Modify.js
  src/pages/Key/Normal.js
  src/pages/Key/utils/useKey.js
  src/popUp/Key/Delete.js
Labels: ✨ Feat

#24 [Chore/#23] Toast UI 버전 호환 문제로 인한 actions 설정 변경
  .github/workflows/tempDeploy.yml
Labels: 📐 Chore

#25 [Feat/#18] Axios 작성 후 주석 처리
  src/api/changeResvAxios.js
  src/api/parkingMapAxios.js
  src/pages/Map/ParkingMap/ParkingMap.js
  src/pages/Map/ParkingMap/colorSet.js
  src/pages/Map/ParkingMap/option.js
  src/pages/Reservation/CarList/CarList.js
  src/pages/Reservation/CarList/utils/useCarList.js
  src/pages/Reservation/ResvList/utils/useResvList.js
Labels: ✨ Feat

#26 [Feat/#22] 차량 상태 관리 axios 구현
  src/api/carStateAxios.js
  src/pages/CarState/CarState.js
  src/pages/CarState/utils/useCarState.js
  src/recoil/carStateAtom.js
Labels: ✨ Feat

#30 [Feat/#28] 주차장 약도 API 연결
  src/api/parkingMapAxios.js
  src/pages/Map/ParkingMap/ParkingMap.js
  src/recoil/adminAtom.js
Labels: ✨ Feat

#31 [Feat/#27] 차량 관리 axios 구현
  src/api/carAxios.js
  src/pages/Car/Car.js
  src/pages/Car/utils/useCar.js
  src/pages/ManageCar/DefaultInfo.js
  src/pages/ManageCar/ManageCar.js
  src/popUp/Car/Delete.js
  src/recoil/carAtom.js
  src/recoil/manageCarAtom.js
Labels: ✨ Feat

#33 [Feat/#32] 차 키 관리 axios 구현
  src/api/keyAxios.js
  src/pages/Key/Key.js
  src/pages/Key/Modify.js
  src/pages/Key/Normal.js
  src/pages/Key/title.js
  src/pages/Key/utils/useKey.js
  src/popUp/Key/Delete.js
  src/recoil/keyAtom.js
Labels: ✨ Feat

#35 [Chore/#34] 프로젝트 세팅 변경
  .github/workflows/tempDeploy.yml
  src/api/interceptors.js
Labels: 📐 Chore

#38 [Feat/#36] 포인트 관리 axios 구현
  src/api/pointAxios.js
  src/pages/ManageCar/DefaultInfo.js
  src/pages/Point/Record.js
  src/pages/Point/Search.js
  src/popUp/Point/Change.js
  src/recoil/pointAtom.js
Labels: ✨ Feat

#41 [Feat/#39] 공지사항 관리 axios 구현
  src/api/noticeAxios.js
  src/pages/ManageNotice/ManageNotice.js
  src/pages/Notice/Notice.js
  src/pages/Notice/utils/useNotice.js
  src/popUp/Notice/Delete.js
  src/recoil/noticeAtom.js
Labels: ✨ Feat

#44 [Feat/#42] 관리자 로그인 ui 추가
  src/api/loginAxios.js
  src/pages/Login/Login.js
Labels: ✨ Feat

#47 [Feat/#46] 지도 변경 상태 저장 버튼 클릭 시 alert 출력
  src/pages/Map/ParkingMap/ParkingMap.js
Labels: ✨ Feat

#49 [Feat/#43] 리스트 정렬 구현
  src/pages/Car/utils/useCar.js
  src/pages/CarState/CarState.js
  src/pages/CarState/utils/useCarState.js
  src/pages/Key/utils/useKey.js
  src/pages/Notice/utils/useNotice.js
Labels: ✨ Feat

#51 [Fix/#50] date 포맷 수정
  src/pages/ManageCar/Accident.js
  src/pages/ManageCar/Repair.js
Labels: 🔧 Fix

#54 [Fix/#50] 상태 변경 시 UI 버그 수정
  src/pages/CarState/CarState.js
Labels: 🔧 Fix

#53 [Fix/#48] 리스트 검색 시 결과 없으면 alert로 없다고 출력
  src/pages/Reservation/CarList/CarList.js
  src/pages/Reservation/Reservation.js
  src/pages/Reservation/ResvList/ResvList.js
Labels: 🔧 Fix

#56 [Feat/#55] 차량 관리 UI 추가 구현 및 버그 수정
  src/pages/ManageCar/DefaultInfo.js
  src/pages/ManageCar/DetailInfo.js
  src/pages/ManageCar/ManageCar.js
Labels: ✨ Feat

#58 [Feat/#57] 차 키 관리 로직 추가 구현 및 버그 수정
  src/pages/Key/Key.js
  src/pages/Key/Modify.js
  src/pages/Key/Normal.js
  src/pages/Key/utils/useKey.js
Labels: ✨ Feat

#60 [Feat/#59] 데이터 유효성 검사
  src/pages/Key/Modify.js
  src/pages/ManageCar/ManageCar.js
  src/pages/ManageNotice/ManageNotice.js
Labels: ✨ Feat

#62 [Feat/#61] 관리자 로그인 적용
  src/App.js
  src/components/SideBar.js
  src/pages/Login/Login.js
  src/recoil/adminAtom.js
Labels: ✨ Feat

#64 [Fix/#63] 유효성 검사 버그 수정
  src/pages/ManageCar/ManageCar.js
Labels: 🔧 Fix

#66 [Fix/#65] 신규 차량 등록 버그 수정
  src/pages/ManageCar/ManageCar.js
  src/recoil/manageCarAtom.js
Labels: 🔧 Fix
